### ISSUE TITLE
Use `main` instead of `master` in message template

### ISSUE THREAD

**Issue by tribut** [paperless-ngx/secretary#5]
We're still talking about the master branch here:

https://github.com/paperless-ngx/secretary/blob/83f640255f0f3b991389ebdb608dd9932b0602b7/api/pr.py#L56

Should be `main`. For some reason I can't push to or fork this repo, so no PR :)

**Comment by bauerj** [comment]
Thanks 😊

I've changed the repo settings so that members of the ci-cd team have write access now.
